### ISSUE TITLE
Searching with ctrl-F often gets stuck in an infinite(?) loop with 100% CPU usage

### ISSUE THREAD

**Issue by andreasvc** [nilsreiter/CorefAnnotator#188] opened 2019-03-27 20:34 UTC
How to reproduce: take an annotated file, search for something, change things, search again. After a few iterations the application becomes unresponsive while typing a new query. Must kill application and lose unsaved work.

This might be the same as #70; reproduced on 1.9.1 though.

**Comment by nilsreiter** [comment] 2019-03-29 17:40
Yes, this is a duplicate of #70. I still don't know why this occurs. But I know it's annoying ...

**Closed by nilsreiter** 2019-03-29 17:40 UTC
Labels: duplicate
