### ISSUE TITLE
Copy of mention when renaming

### ISSUE THREAD

**Issue by melandresen** [nilsreiter/CorefAnnotator#141] opened 2018-07-18 09:46 UTC
When I add I new entity and rename it, the mention is copied. Example: I take the string "meine Kleine" and drag it on "New Entity". I rename the entity to "Tochter von Lizzie". As a result, I have an entity called "Tochter von Lizzie" with two mentions, both of them referring to the string "meine Kleine". 
I think this happens only when I do not save before renaming.

**Comment by nilsreiter** [comment] 2018-09-06 05:56
Funny thing, this is caused by the rename dialog, but only if you activate it via the context menu (shortcut should be fine) and close it by pressing enter on the keyboard (clicking the dialog button should be fine). When the dialog is open, the tree view is still the active component. It receives the enter key event and interprets it as "add the currently selected span as a mention to the currently selected entity". Will be fixed in 1.5.5

**Comment by nilsreiter** [comment] 2018-09-06 06:45
Will be fixed in 1.5.5

**Closed** 2018-09-06 07:34 UTC
Labels: 1.5.x, bug
